import React, { useState, useEffect } from 'react';
import {
  Box,
  Card,
  Grid,
  Typography,
  Button,
  TextField
} from '@mui/material';
import MDBox from 'components/MDBox';
import MDTypography from 'components/MDTypography';
import FrontendLayout from "layouts/frontend";
import axios from 'axios';
import DashboardSidebar from './DashboardSidebar';

const HelpSupport = () => {
  const [userInfo, setUserInfo] = useState(null);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState('');

  useEffect(() => {
    const fetchUserInfo = async () => {
      try {
        const token = localStorage.getItem('token');
        const response = await axios.get(`${process.env.REACT_APP_API_URL}/me`, {
          headers: {
            Authorization: `Bearer ${token}`
          }
        });
        setUserInfo(response.data.data.userInfo);
      } catch (error) {
        console.error('Error fetching user info:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchUserInfo();
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const token = localStorage.getItem('token');
      await axios.post(`${process.env.REACT_APP_API_URL}/support-ticket`, 
        { message },
        {
          headers: {
            Authorization: `Bearer ${token}`
          }
        }
      );
      setMessage('');
      // Show success message
    } catch (error) {
      console.error('Error submitting support ticket:', error);
    }
  };

  if (loading) {
    return (
      <FrontendLayout>
        <MDBox>
          <Typography>Loading...</Typography>
        </MDBox>
      </FrontendLayout>
    );
  }

  return (
    <FrontendLayout>
      <MDBox>
        <Grid container spacing={3}>
          {/* Left Sidebar */}
          <Grid item xs={12} md={3}>
            <DashboardSidebar userInfo={userInfo} />
          </Grid>

          {/* Main Content Area */}
          <Grid item xs={12} md={9}>
            <Card sx={{ p: 3, backgroundColor: 'white' }}>
              <MDTypography variant="h5" color="dark" mb={3}>
                Help & Support
              </MDTypography>

              {/* Section 1 */}
              <Box sx={{ mb: 3 }}>
                <Typography variant="h6" fontWeight="medium" gutterBottom>
                  1. Identify customer's common problems
                </Typography>
                <Typography variant="body2">
                  Customers often turn to your help center for answers about your products or services, making it crucial to identify their common questions and concerns as a foundation for building an effective support page. To achieve this, tapping into the data generated by customer searches and inquiries is invaluable.
                </Typography>
              </Box>

              {/* Section 2 */}
              <Box sx={{ mb: 3 }}>
                <Typography variant="h6" fontWeight="medium" gutterBottom>
                  2. Live support chat
                </Typography>
                <Typography variant="body2">
                  Integrating a live chat feature onto your webpage can be a game-changer for enhancing customer support and satisfaction. Add contact forms on your support page and allow customers to find solutions quicker by texting your support agent.
                </Typography>
              </Box>

              {/* Section 3 */}
              <Box sx={{ mb: 3 }}>
                <Typography variant="h6" fontWeight="medium" gutterBottom>
                  3. I forgot my password. What should I do?
                </Typography>
                <Typography variant="body2">
                  ClusterCS may aggregate data we acquire about our Customers and their End Users, including the Log Database and Server Usage and Contents described above. For example, we may assemble data to determine whether attacks are being performed against servers and applications of our Customers or their End Users, to identify common applications and application versions, to identify server and application performance profiles, or to compile information and statistics for informational or marketing purposes.
                </Typography>
              </Box>

              {/* Section 4 */}
              <Box sx={{ mb: 3 }}>
                <Typography variant="h6" fontWeight="medium" gutterBottom>
                  4. How can I update my account information?
                </Typography>
                <Typography variant="body2">
                  We store your information in Romania, country member of the European Union. If you are accessing or using our Websites or Services or otherwise providing information to us, you are agreeing to the transfer of your personal information to Romania. ClusterCS is subject to the investigatory and enforcement powers governed by the laws in action in the European Union.
                </Typography>
              </Box>

              {/* Section 5 */}
              <Box sx={{ mb: 3 }}>
                <Typography variant="h6" fontWeight="medium" gutterBottom>
                  5. International Information Transfers
                </Typography>
                <Typography variant="body2">
                  We store your information in Romania, country member of the European Union. If you are accessing or using our Websites or Services or otherwise providing information to us, you are agreeing to the transfer of your personal information to Romania. ClusterCS is subject to the investigatory and enforcement powers governed by the laws in action in the European Union.
                </Typography>
              </Box>

              {/* Section 6 */}
              <Box sx={{ mb: 3 }}>
                <Typography variant="h6" fontWeight="medium" gutterBottom>
                  6. Notification Of Changes
                </Typography>
                <Typography variant="body2">
                  This Privacy Policy is subject to occasional revision, and if any substantial changes are made to the way your Personal Data is used, we will notify you by email to the email address that you have provided as being the most current posting the notice of such changes on our website. Any changes to the Privacy Policy will be effective upon the earlier of either thirty (30) calendar days from the dispatch of the email notice to you or thirty (30) calendar days following our posting of the update terms on our website, or the date on which you accept the terms by clicking "I Accept" or similar means. These changes will be effective immediately for any new users and customers of our website and related products and services. Please note that you are responsible at all times for updating your Personal Data and with providing us with your most recent and current email address. In the event that the email address is no longer valid the date at which the proposed changes were dispatched will still constitute effective notice of any changes to the Privacy Policy. If you do not wish to permit changes in our use of your Personal Data you must notify us prior to the effective date of the changes and that you wish to deactivate your account. Continued use of our website, products, and or related services, following notice of any such changes shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes.
                </Typography>
              </Box>

              {/* Section 7 */}
              <Box sx={{ mb: 3 }}>
                <Typography variant="h6" fontWeight="medium" gutterBottom>
                  7. Business Transactions
                </Typography>
                <Typography variant="body2">
                  We may assign or transfer this Policy, as well as information covered by this Policy, in the event of a merger, sale, change in control, or reorganization of all our part of our business.
                </Typography>
              </Box>

              {/* Section 8 */}
              <Box sx={{ mb: 3 }}>
                <Typography variant="h6" fontWeight="medium" gutterBottom>
                  8. Contact Informations
                </Typography>
                <Typography variant="body2">
                  If you have any questions about this Privacy Policy, you can contact us by email at <Box component="span" sx={{ color: 'primary.main', fontWeight: 'medium' }}>office@loghic.com</Box>
                </Typography>
              </Box>

              <Box sx={{ mt: 4 }}>
                <MDTypography variant="h6" color="dark" mb={2}>
                  Contact Support
                </MDTypography>
                <form onSubmit={handleSubmit}>
                  <TextField
                    fullWidth
                    multiline
                    rows={4}
                    label="How can we help?"
                    value={message}
                    onChange={(e) => setMessage(e.target.value)}
                    sx={{ mb: 2 }}
                  />
                  <Button
                    type="submit"
                    variant="contained"
                    sx={{
                      backgroundColor: '#213a93',
                      '&:hover': { backgroundColor: '#1a2d75' }
                    }}
                  >
                    Submit
                  </Button>
                </form>
              </Box>
            </Card>
          </Grid>
        </Grid>
      </MDBox>
    </FrontendLayout>
  );
};

export default HelpSupport; 